<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Diros</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.AudioModule" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="0Harmony" />
    <Reference Include="UnityEngine.XRModule" />
    <Reference Include="BepInEx" />
    <Reference Include="Unity.InputSystem" />
    <Reference Include="UnityEngine.UI" />
  </ItemGroup>
</Project>
